version: "3.9"

services:
  batch-ingestion-service:
    build:
      context: ./batch_ingestion
      dockerfile: Dockerfile
    env_file:
      - .env
    profiles:
      - manual
    depends_on:
      - embedding-service

  embedding-service:
    build:
      context: ./embedding
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"

  retrieval-service:
    build:
      context: ./retrieval
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - embedding-service
      - llm-generation-service

  llm-generation-service:
    build:
      context: ./llm_generation
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
